# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'NonRegUsrScreen.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_NonRegUserScreen(object):
    def setupUi(self, NonRegUserScreen):
        NonRegUserScreen.setObjectName("NonRegUserScreen")
        NonRegUserScreen.resize(792, 171)
        self.pushButton = QtWidgets.QPushButton(NonRegUserScreen)
        self.pushButton.setGeometry(QtCore.QRect(200, 110, 141, 31))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(12)
        self.pushButton.setFont(font)
        self.pushButton.setObjectName("pushButton")
        self.lineEdit = QtWidgets.QLineEdit(NonRegUserScreen)
        self.lineEdit.setGeometry(QtCore.QRect(180, 60, 431, 41))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(12)
        self.lineEdit.setFont(font)
        self.lineEdit.setText("")
        self.lineEdit.setObjectName("lineEdit")
        self.entername = QtWidgets.QLabel(NonRegUserScreen)
        self.entername.setGeometry(QtCore.QRect(100, 10, 591, 41))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(20)
        font.setKerning(False)
        self.entername.setFont(font)
        self.entername.setAlignment(QtCore.Qt.AlignCenter)
        self.entername.setObjectName("entername")

        self.pushButton_2 = QtWidgets.QPushButton(NonRegUserScreen)
        self.pushButton_2.setGeometry(QtCore.QRect(450, 110, 141, 31))
        self.pushButton_2.clicked.connect(lambda: self.close())

        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(12)
        self.pushButton_2.setFont(font)
        self.pushButton_2.setObjectName("pushButton_2")

        self.retranslateUi(NonRegUserScreen)
        QtCore.QMetaObject.connectSlotsByName(NonRegUserScreen)

    def retranslateUi(self, NonRegUserScreen):
        _translate = QtCore.QCoreApplication.translate
        NonRegUserScreen.setWindowTitle(_translate("NonRegUserScreen", "Dialog"))
        self.pushButton.setText(_translate("NonRegUserScreen", "Submit"))
        self.entername.setText(_translate("NonRegUserScreen", "Welcome! Please enter your name:"))
        self.pushButton_2.setText(_translate("NonRegUserScreen", "Return"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    NonRegUserScreen = QtWidgets.QDialog()
    ui = Ui_NonRegUserScreen()
    ui.setupUi(NonRegUserScreen)
    NonRegUserScreen.show()
    sys.exit(app.exec_())
